/**
 * Fildlab Perú S.A.C. - Enums del Dominio (SI_FILDLAB-2026)
 */

export enum UserRole {
  GERENCIA = 'GERENCIA',
  TECNICO = 'TECNICO'
}

export enum ContractStatus {
  ACTIVO = 'ACTIVO',
  SUSPENDIDO = 'SUSPENDIDO',
  VENCIDO = 'VENCIDO',
  ANULADO = 'ANULADO'
}

export enum EquipmentType {
  OSMOSIS_INVERSA = 'OSMOSIS_INVERSA',
  ABLANDADOR = 'ABLANDADOR',
  FILTRO_MULTIMEDIA = 'FILTRO_MULTIMEDIA',
  DESIONIZADOR = 'DESIONIZADOR',
  SISTEMA_UV = 'SISTEMA_UV'
}

export enum EquipmentStatus {
  OPERATIVO = 'OPERATIVO',
  MANTENIMIENTO_REQUERIDO = 'MANTENIMIENTO_REQUERIDO',
  CRITICO = 'CRITICO',
  FUERA_DE_SERVICIO = 'FUERA_DE_SERVICIO'
}

export enum ServiceType {
  PREVENTIVO = 'PREVENTIVO',
  CORRECTIVO = 'CORRECTIVO',
  EMERGENCIA = 'EMERGENCIA',
  INSTALACION = 'INSTALACION'
}

export enum OrderStatus {
  PENDIENTE = 'PENDIENTE',
  EN_PROCESO = 'EN_PROCESO',
  CERRADA_CAMPO = 'CERRADA_CAMPO',
  SINCRONIZADA = 'SINCRONIZADA',
  LIQUIDADA_APROBADA = 'LIQUIDADA_APROBADA',
  ANULADA = 'ANULADA'
}

export enum WorkOrderSpareStatus {
  UTILIZADO_CAMPO = 'UTILIZADO_CAMPO',                       // Fase 1: En IndexedDB local
  COMPROMETIDO_EN_TRANSITO = 'COMPROMETIDO_EN_TRANSITO',     // Fase 2: Al sincronizar
  LIQUIDADO_DESCONTADO = 'LIQUIDADO_DESCONTADO'              // Fase 3: Aprobado por Gerencia
}

export enum SpareMovementType {
  ENTRADA_CENTRAL = 'ENTRADA_CENTRAL',
  ASIGNACION_A_TECNICO = 'ASIGNACION_A_TECNICO',
  DEVOLUCION_A_CENTRAL = 'DEVOLUCION_A_CENTRAL',
  CONSUMO_EN_ORDEN = 'CONSUMO_EN_ORDEN',
  AJUSTE_INVENTARIO = 'AJUSTE_INVENTARIO'
}

export enum MlAuditErrorType {
  OUT_OF_PHYSICAL_RANGE = 'OUT_OF_PHYSICAL_RANGE',
  INCOMPLETE_FEATURES = 'INCOMPLETE_FEATURES',
  MODEL_INFERENCE_EXCEPTION = 'MODEL_INFERENCE_EXCEPTION'
}
